<?php

namespace App\Enums;

enum AuditActionEnum: string
{
    case REGISTERED = 'REGISTERED';
    case EMAIL_VERIFIED = 'EMAIL_VERIFIED';
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case TOKEN_REFRESHED = 'TOKEN_REFRESHED';
    case OTP_SENT = 'OTP_SENT';
    case OTP_VERIFIED = 'OTP_VERIFIED';
    case OTP_FAILED = 'OTP_FAILED';
    case PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case PROFILE_UPDATED = 'PROFILE_UPDATED';

    case CAMPAIGN_CREATED = 'CAMPAIGN_CREATED';
    case CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED';
    case CAMPAIGN_ACTIVATED = 'CAMPAIGN_ACTIVATED';
    case CAMPAIGN_PAUSED = 'CAMPAIGN_PAUSED';
    case CAMPAIGN_RESUMED = 'CAMPAIGN_RESUMED';
    case CAMPAIGN_DEACTIVATED = 'CAMPAIGN_DEACTIVATED';
    case CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED';
    case CAMPAIGN_DELETED = 'CAMPAIGN_DELETED';
    case CAMPAIGN_REPORT_GENERATED = 'CAMPAIGN_REPORT_GENERATED';
    case BULK_EMAIL_CREATED = 'BULK_EMAIL_CREATED';
    case BULK_EMAIL_SENT = 'BULK_EMAIL_SENT';
    case BULK_EMAIL_DELETED = 'BULK_EMAIL_DELETED';
    case BULK_EMAIL_SET_ACTIVE = 'BULK_EMAIL_SET_ACTIVE';

    case ADMIN_CREATED = 'ADMIN_CREATED';
    case ADMIN_UPDATED = 'ADMIN_UPDATED';
    case ADMIN_STATUS_TOGGLED = 'ADMIN_STATUS_TOGGLED';
    case ADMIN_INVITE_LINK_RESENT = 'ADMIN_INVITE_LINK_RESENT';
    case ADMIN_DELETED = 'ADMIN_DELETED';
    case ROLE_CREATED = 'ROLE_CREATED';
    case ROLE_UPDATED = 'ROLE_UPDATED';
    case ROLE_STATUS_TOGGLED = 'ROLE_STATUS_TOGGLED';
    case ROLE_DELETED = 'ROLE_DELETED';

    case PLEDGE_REMINDER_SENT = 'PLEDGE_REMINDER_SENT';

    case ABOUT_SECTION_UPDATED = 'ABOUT_SECTION_UPDATED';
    case ABOUT_SECTION_STATUS_TOGGLED = 'ABOUT_SECTION_STATUS_TOGGLED';

    case HERO_SLIDE_CREATED = 'HERO_SLIDE_CREATED';
    case HERO_SLIDE_UPDATED = 'HERO_SLIDE_UPDATED';
    case HERO_SLIDE_STATUS_TOGGLED = 'HERO_SLIDE_STATUS_TOGGLED';
    case HERO_SLIDE_DELETED = 'HERO_SLIDE_DELETED';

    case AD_CREATED = 'AD_CREATED';
    case AD_UPDATED = 'AD_UPDATED';
    case AD_ARCHIVED = 'AD_ARCHIVED';
    case AD_REACTIVATED = 'AD_REACTIVATED';
    case AD_DELETED = 'AD_DELETED';
    case AD_IMAGES_UPDATED = 'AD_IMAGES_UPDATED';
    case AD_IMAGE_DELETED = 'AD_IMAGE_DELETED';
    case AD_SETTINGS_UPDATED = 'AD_SETTINGS_UPDATED';

    case FAQ_CREATED = 'FAQ_CREATED';
    case FAQ_UPDATED = 'FAQ_UPDATED';
    case FAQ_STATUS_TOGGLED = 'FAQ_STATUS_TOGGLED';
    case FAQ_DELETED = 'FAQ_DELETED';

    case EVENT_CREATED = 'EVENT_CREATED';
    case EVENT_UPDATED = 'EVENT_UPDATED';
    case EVENT_STATUS_CHANGED = 'EVENT_STATUS_CHANGED';
    case EVENT_DELETED = 'EVENT_DELETED';
    case EVENT_IMAGES_UPDATED = 'EVENT_IMAGES_UPDATED';
    case EVENT_IMAGE_DELETED = 'EVENT_IMAGE_DELETED';

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }
}
