<?php

namespace App\Enums;

enum AuditActionEnum: string
{
    case REGISTERED = 'REGISTERED';
    case EMAIL_VERIFIED = 'EMAIL_VERIFIED';
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case OTP_SENT = 'OTP_SENT';
    case OTP_VERIFIED = 'OTP_VERIFIED';
    case OTP_FAILED = 'OTP_FAILED';
    case PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case PROFILE_UPDATED = 'PROFILE_UPDATED';

    case CAMPAIGN_CREATED = 'CAMPAIGN_CREATED';
    case CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED';
    case CAMPAIGN_ACTIVATED = 'CAMPAIGN_ACTIVATED';
    case CAMPAIGN_PAUSED = 'CAMPAIGN_PAUSED';
    case CAMPAIGN_RESUMED = 'CAMPAIGN_RESUMED';
    case CAMPAIGN_DEACTIVATED = 'CAMPAIGN_DEACTIVATED';
    case CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED';
    case CAMPAIGN_DELETED = 'CAMPAIGN_DELETED';
    case CAMPAIGN_REPORT_GENERATED = 'CAMPAIGN_REPORT_GENERATED';
    case BULK_EMAIL_CREATED = 'BULK_EMAIL_CREATED';
    case BULK_EMAIL_SENT = 'BULK_EMAIL_SENT';
    case BULK_EMAIL_DELETED = 'BULK_EMAIL_DELETED';
    case BULK_EMAIL_SET_ACTIVE = 'BULK_EMAIL_SET_ACTIVE';

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }
}
